### ISSUE TITLE
可以加自定义prompt提示词功能吗

### ISSUE THREAD

**Issue by czh020110** [pot-app/pot-app-recognize-plugin-openai#1]
作者大大可以加自定义prompt提示词功能吗，有时候识别会对图片做解释或者显示英文，我觉得和翻译一样加个自定义提示要求会更能按要求识别图片。

**Comment by Pylogmon** [comment]
https://github.com/pot-app/pot-app-recognize-plugin-openai/releases/tag/2.0.1
